version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10
    groups:
      docker:
        patterns:
          - '*docker*'

  # Maintain dependencies for Docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: node
        versions: ['>20.11']

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - '*eslint*'
    ignore:
      - dependency-name: '@types/node'
        versions: ['>20.11']
