# Example workflow for running cron jobs

name: Nightly

on:
  schedule:
    #       ┌───────────── minute (0 - 59)
    #       │ ┌───────────── hour (0 - 23)
    #       │ │ ┌───────────── day of the month (1 - 31)
    #       │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #       │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       * * * * *
    - cron: 0 0 1 * * # Example: change to `0 0 * * 1-5` in order to run every working day
  workflow_dispatch: {}

permissions: {}

jobs:
  trunk_check_upload:
    name: Trunk Check Upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Setup NodeJS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.11.1
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Generate types
        run: npm run codecept:types
        env:
          TESTS_MOBILE_COMMON_LAUNCH_TYPE: ${{ vars.TESTS_MOBILE_COMMON_LAUNCH_TYPE }}
          TESTS_MOBILE_COMMON_USER_PASSWORD: ${{ secrets.TESTS_MOBILE_COMMON_USER_PASSWORD }}
          TESTS_MOBILE_COMMON_USER_USERNAME: ${{ secrets.TESTS_MOBILE_COMMON_USER_USERNAME }}
          TESTS_MOBILE_LOCAL_APP_PATH: ${{ vars.TESTS_MOBILE_LOCAL_APP_PATH }}
          TESTS_MOBILE_LOCAL_PLATFORM: ${{ vars.TESTS_MOBILE_LOCAL_PLATFORM }}
          TESTS_MOBILE_LOCAL_DEVICE: ${{ vars.TESTS_MOBILE_LOCAL_DEVICE }}
      - name: Trunk Check
        uses: trunk-io/trunk-action@540e7fe497a45ae76370d26d95cc249059c4ac3a # v1.1.12
        with:
          check-mode: all
          # trunk-token: ${{ secrets.TRUNK_TOKEN }}
          # arguments: --replace # TODO: remove later - https://features.trunk.io/check/p/uploads-should-not-error-out-if-results-have-already-been-uploaded

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Setup NodeJS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.11.1
          cache: npm
      - name: Install package dependencies
        run: npm ci --production
      # - name: Run all tests
      #   run: npm run test
      # - name: Run backend tests
      #   run: npm run test:api
      # - name: Run infrastructure tests
      #   run: npm run test:infra
      # - name: Run mobile tests
      #   run: npm run test:mobile
      - name: Run web tests
        run: npm run test:web
      - name: Upload test artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: always()
        with:
          name: test-reports
          path: reports/
          retention-days: 30
