# Example workflow for checking PRs and commits

name: Pull Request or Push to master

on:
  pull_request: {}
  push:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      checks: write # For Trunk to post annotations
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Setup NodeJS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.11.1
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Generate types
        run: npm run codecept:types
        env:
          TESTS_MOBILE_COMMON_LAUNCH_TYPE: ${{ vars.TESTS_MOBILE_COMMON_LAUNCH_TYPE }}
          TESTS_MOBILE_COMMON_USER_PASSWORD: ${{ secrets.TESTS_MOBILE_COMMON_USER_PASSWORD }}
          TESTS_MOBILE_COMMON_USER_USERNAME: ${{ secrets.TESTS_MOBILE_COMMON_USER_USERNAME }}
          TESTS_MOBILE_LOCAL_APP_PATH: ${{ vars.TESTS_MOBILE_LOCAL_APP_PATH }}
          TESTS_MOBILE_LOCAL_PLATFORM: ${{ vars.TESTS_MOBILE_LOCAL_PLATFORM }}
          TESTS_MOBILE_LOCAL_DEVICE: ${{ vars.TESTS_MOBILE_LOCAL_DEVICE }}
      - name: Trunk Check
        uses: trunk-io/trunk-action@540e7fe497a45ae76370d26d95cc249059c4ac3a # v1.1.12

  build_check:
    name: Build Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Setup NodeJS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.11.1
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Generate types
        run: npm run codecept:types
        env:
          TESTS_MOBILE_COMMON_LAUNCH_TYPE: ${{ vars.TESTS_MOBILE_COMMON_LAUNCH_TYPE }}
          TESTS_MOBILE_COMMON_USER_PASSWORD: ${{ secrets.TESTS_MOBILE_COMMON_USER_PASSWORD }}
          TESTS_MOBILE_COMMON_USER_USERNAME: ${{ secrets.TESTS_MOBILE_COMMON_USER_USERNAME }}
          TESTS_MOBILE_LOCAL_APP_PATH: ${{ vars.TESTS_MOBILE_LOCAL_APP_PATH }}
          TESTS_MOBILE_LOCAL_PLATFORM: ${{ vars.TESTS_MOBILE_LOCAL_PLATFORM }}
          TESTS_MOBILE_LOCAL_DEVICE: ${{ vars.TESTS_MOBILE_LOCAL_DEVICE }}
      - name: Run build check
        run: npm run dist:check

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Setup NodeJS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.11.1
          cache: npm
      - name: Install package dependencies
        run: npm ci --production
      # - name: Run all tests
      #   run: npm run test
      # - name: Run backend tests
      #   run: npm run test:api
      # - name: Run infrastructure tests
      #   run: npm run test:infra
      # - name: Run mobile tests
      #   run: npm run test:mobile
      - name: Run web tests
        run: npm run test:web
      - name: Upload test artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: always()
        with:
          name: test-reports
          path: reports/
          retention-days: 30
